import { TemplateConfig } from './types'

export const TEMPLATES: TemplateConfig[] = [
  {
    id: 'warm-spring',
    name: '따뜻한 봄날',
    description: '수채화 꽃과 함께하는 따뜻한 자서전',
    thumbnail: '/templates/warm-spring.png',
    category: 'nature',
    font: 'NanumMyeongjo',
    colors: {
      primary: '#E8A87C',
      secondary: '#D4A574',
      background: '#FFF8F0',
      text: '#3E2723',
      accent: '#E57373',
    },
  },
  {
    id: 'ink-painting',
    name: '고요한 수묵',
    description: '전통 수묵화 느낌의 고즈넉한 자서전',
    thumbnail: '/templates/ink-painting.png',
    category: 'traditional',
    font: 'KoPubBatang',
    colors: {
      primary: '#4A4A4A',
      secondary: '#8B7355',
      background: '#F5F0E8',
      text: '#2C2C2C',
      accent: '#6D4C41',
    },
  },
  {
    id: 'modern-minimal',
    name: '모던 미니멀',
    description: '깔끔하고 현대적인 디자인',
    thumbnail: '/templates/modern-minimal.png',
    category: 'modern',
    font: 'Pretendard',
    colors: {
      primary: '#2C3E50',
      secondary: '#7F8C8D',
      background: '#FFFFFF',
      text: '#2C3E50',
      accent: '#3498DB',
    },
  },
  {
    id: 'autumn-study',
    name: '가을 서재',
    description: '따뜻한 갈색톤의 서재 느낌',
    thumbnail: '/templates/autumn-study.png',
    category: 'classic',
    font: 'NanumBarunGothic',
    colors: {
      primary: '#8B4513',
      secondary: '#D2691E',
      background: '#FDF5E6',
      text: '#3E2723',
      accent: '#A0522D',
    },
  },
  {
    id: 'sky-letter',
    name: '하늘빛 편지',
    description: '밝고 맑은 하늘색 편지지 스타일',
    thumbnail: '/templates/sky-letter.png',
    category: 'nature',
    font: 'NanumPen',
    colors: {
      primary: '#5DADE2',
      secondary: '#85C1E9',
      background: '#EBF5FB',
      text: '#1B4F72',
      accent: '#2E86C1',
    },
  },
  {
    id: 'golden-album',
    name: '골든 앨범',
    description: '금색 테두리의 고급스러운 디자인',
    thumbnail: '/templates/golden-album.png',
    category: 'classic',
    font: 'NanumMyeongjo',
    colors: {
      primary: '#D4AC0D',
      secondary: '#F4D03F',
      background: '#FFFDE7',
      text: '#4A4A2A',
      accent: '#C9960C',
    },
  },
  {
    id: 'wildflower',
    name: '들꽃 산책',
    description: '자연의 들꽃과 함께하는 보타니컬 디자인',
    thumbnail: '/templates/wildflower.png',
    category: 'nature',
    font: 'MaruBuri',
    colors: {
      primary: '#27AE60',
      secondary: '#82E0AA',
      background: '#F0FFF0',
      text: '#1B5E20',
      accent: '#4CAF50',
    },
  },
  {
    id: 'retro-diary',
    name: '청춘 일기',
    description: '복고풍 레트로 감성의 일기장',
    thumbnail: '/templates/retro-diary.png',
    category: 'classic',
    font: 'Gothic',
    colors: {
      primary: '#6C3483',
      secondary: '#AF7AC5',
      background: '#F8F0FF',
      text: '#4A235A',
      accent: '#8E44AD',
    },
  },
  {
    id: 'moonlight',
    name: '달빛 이야기',
    description: '밤하늘과 달빛의 몽환적 디자인',
    thumbnail: '/templates/moonlight.png',
    category: 'nature',
    font: 'KoPubBatang',
    colors: {
      primary: '#1A237E',
      secondary: '#5C6BC0',
      background: '#E8EAF6',
      text: '#1A237E',
      accent: '#3F51B5',
    },
  },
  {
    id: 'pure-white',
    name: '순백의 기록',
    description: '깨끗한 화이트 배경의 심플 디자인',
    thumbnail: '/templates/pure-white.png',
    category: 'modern',
    font: 'Pretendard',
    colors: {
      primary: '#2C3E50',
      secondary: '#ECF0F1',
      background: '#FFFFFF',
      text: '#2C3E50',
      accent: '#95A5A6',
    },
  },
]

export function getTemplate(id: string): TemplateConfig | undefined {
  return TEMPLATES.find(t => t.id === id)
}
